services:
  nilcc-attester:
    image: ghcr.io/nillionnetwork/nilcc-attester:latest
    restart: unless-stopped
    environment:
      APP__SERVER__BIND_ENDPOINT: "0.0.0.0:80"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]

  nilcc-proxy:
    image: caddy:2
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${CADDY_INPUT_FILE}:/etc/caddy/Caddyfile

