agent_id: "dc96ffc5-2424-4809-b5cb-3eb405e6f519"
vm_store: /tmp

qemu:
  system_bin: qemu-system-x86_64
  img_bin: qemu-img

api:
  bind_endpoint: "127.0.0.1:50055"

controller:
  endpoint: "http://127.0.0.1:8081"
  key: your-metal-instance-api-key
  sync_interval: 10s

db:
  url: "sqlite://:memory:"

cvm:
  initrd: /tmp/artifacts/initramfs.cpio
  bios: /tmp/artifacts/OVMF.fd
  cpu:
    kernel: /tmp/artifacts/vmlinuz
    base_disk: /tmp/artifacts/disk.qcow2
    verity_disk: /tmp/artifacts/verity-hash-dev.raw
    verity_root_hash: /proc/version
  gpu:
    kernel: /tmp/artifacts/vmlinuz-gpu
    base_disk: /tmp/artifacts/disk-gpu.qcow2
    verity_disk: /tmp/artifacts/verity-hash-dev-gpu.raw
    verity_root_hash: /proc/version

sni_proxy:
  dns_subdomain: "localhost"
  start_port_range: 10000
  end_port_range: 20000
  config_file_path: /etc/haproxy/haproxy.cfg
  ha_proxy_config_reload_command: sudo systemctl reload haproxy
  timeouts:
    connect: 5000
    server: 5000
    client: 5000
  max_connections: 100000

metrics:
  bind_endpoint: 0.0.0.0:9092

resources:
  reserved:
    cpus: 1
    memory_gb: 2
    disk_space_gb: 10

