services:
  nilcc-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nilcc_api
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
      localstack:
        condition: service_started
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nilcc_db
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  localstack:
    container_name: localstack
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
      - "4510-4559:4510-4559" # External services port range
    volumes:
      - "./localstack_data:/var/lib/localstack" # For persistence of data
