#cloud-config
autoinstall:
  version: 1
  identity:
    hostname: nilCC
    username: nillion
    # produced with: echo "nillion" | mkpasswd -m sha-512 -s
    password: "$6$.Uf8tj/pGoGkjrCh$eF6BIaqwEFdsA44YSc0hb1mKzrjJr0HfUb/2zEa/rIetxiDoW1Olya/MUA19Px2GrDK12ocTCme140Er1rUAb/"
  keyboard:
    layout: us
  locale: en_US.UTF-8
  network:
    network:
      ethernets:
        all-eth:
          match:
            name: en*
          dhcp4: true
      version: 2
  storage:
    layout:
      name: direct

  late-commands:
    - curtin in-target -- dpkg -i /cdrom/packages/*.deb
    - curtin in-target -- apt-get update
    - curtin in-target -- apt-get -y install nvidia-driver-550-server-open docker-compose-v2 jq
    - curtin in-target -- bash -c 'echo "install nvidia /sbin/modprobe ecdsa_generic ecdh; /sbin/modprobe --ignore-install nvidia" > /etc/modprobe.d/nvidia-lkca.conf'
    - curtin in-target -- sed -i "/^ExecStart=/d" /usr/lib/systemd/system/nvidia-persistenced.service
    - curtin in-target -- bash -c 'echo "ExecStart=/usr/bin/nvidia-persistenced --user nvidia-persistenced --uvm-persistence-mode --verbose" >> /usr/lib/systemd/system/nvidia-persistenced.service'
    - curtin in-target -- apt purge -y linux-image-6.8* linux-headers-6.8* linux-tools-6.8*
    # Copy over cvm-agent.
    - curtin in-target -- mkdir /opt/nillion
    - curtin in-target -- cp /cdrom/nillion/cvm-agent.sh /opt/nillion
    - curtin in-target -- chmod +x /opt/nillion/cvm-agent.sh
    # Copy services config
    - curtin in-target -- cp -r /cdrom/nillion/services /opt/nillion
    # Configure cvm-agent to auto start.
    - curtin in-target -- cp /cdrom/nillion/cvm-agent.service /etc/systemd/system/
    - curtin in-target -- systemctl daemon-reload
    - curtin in-target -- systemctl enable cvm-agent.service
    # Copy metadata files
    - curtin in-target -- cp /cdrom/nillion/nilcc-version /opt/nillion
    - curtin in-target -- cp /cdrom/nillion/nilcc-vm-type /opt/nillion
    # Remove unattended upgrades
    - curtin in-target -- apt purge -y unattended-upgrades
    # Copy kernel and initrd to host
    - |
      curtin in-target -- bash -c '
        mkdir -p /mnt/shared
        mount -t 9p -o trans=virtio hostshare /mnt/shared
        cp /boot/vmlinuz-*snp* /mnt/shared/
      '
