#cloud-config
autoinstall:
  version: 1
  identity:
    hostname: nilCC
    username: nillion
    # produced with: echo "nillion" | mkpasswd -m sha-512 -s
    password: "$6$.Uf8tj/pGoGkjrCh$eF6BIaqwEFdsA44YSc0hb1mKzrjJr0HfUb/2zEa/rIetxiDoW1Olya/MUA19Px2GrDK12ocTCme140Er1rUAb/"
  keyboard:
    layout: us
  locale: en_US.UTF-8
  network:
    network:
      ethernets:
        all-eth:
          match:
            name: en*
          dhcp4: true
      version: 2
  storage:
    layout:
      name: lvm

  late-commands:
    - curtin in-target -- dpkg -i /cdrom/packages/*.deb
    - curtin in-target -- echo "blacklist nvidia\nblacklist nvidia-drm\nblacklist nvidia-modeset\nblacklist nvidia-uvm\nblacklist nvidiafb\nblacklist nouveau" > tee /etc/modprobe.d/blacklist-nvidia.conf
    - curtin in-target -- echo "vfio_pci" > /etc/modules-load.d/vfio.conf
    - curtin in-target -- cp /cdrom/extra/nvflash /usr/local/bin/
    - curtin in-target -- cp /cdrom/extra/gpu_vfio.sh /usr/local/bin/
    - curtin in-target -- cp /cdrom/extra/amd_sev_fam19h_model1xh_1.55.39.sbin /usr/local/bin/

