name: CD - Publish Docker Image to ECR

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  docker-build-nilcc-attester:
    runs-on: ubuntu-latest
    env:
      DOCKER_TAG: ghcr.io/nillionnetwork/nilcc-attester:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: docker/nilcc-attester.dockerfile
          tags: ${{ env.DOCKER_TAG }}

      - name: Log in to the container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: docker/nilcc-attester.dockerfile
          push: true
          tags: ${{ env.DOCKER_TAG }}
          build-args: |
            VERSION=${{ env.PACKAGE_VERSION }}
