name: Merge checks
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  check:
    name: Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install nightly rust toolchain
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt

      - name: Cargo fmt
        run: cargo +nightly fmt --all -- --check

      - name: Install stable rust toolchain
        uses: dtolnay/rust-toolchain@1.85.0
        with:
          components: clippy

      - name: Install proto compiler
        run: sudo apt-get install -y protobuf-compiler

      - name: Cargo check
        run: cargo check

      - name: Cargo test
        run: cargo test

      - name: Cargo clippy
        run: cargo clippy -- -D warnings
