agent_id: "f7b27e21-eabb-4acb-8cd7-1d8113fd2237"
vm_store: /tmp

qemu:
  system_bin: qemu-system-x86_64
  img_bin: qemu-img

api:
  endpoint: "http://127.0.0.1:50051"
  key: test
  sync_interval: 10s

db:
  url: sqlite:///tmp/db.sqlite

cvm:
  initrd: /tmp/artifacts/initramfs.cpio
  kernel: /tmp/artifacts/vmlinuz
  bios: /tmp/artifacts/OVMF.fd
  base_disk: /tmp/artifacts/disk.qcow2
  verity_disk: /tmp/artifacts/verity-hash-dev.raw
  verity_root_hash: "80d9c99845b2295110259d18684d0daf4720c8837558146e4cc50a4b0a44a18e"

sni_proxy:
  dns_subdomain: "workloads.nilcc.com"
  start_port_range: 10000
  end_port_range: 20000
  config_file_path: /etc/haproxy/haproxy.cfg
  ha_proxy_config_reload_command: sudo systemctl reload haproxy
  timeouts:
    connect: 5s
    server: 5s
    client: 5s
  max_connections: 100000

metrics:
  bind_endpoint: 0.0.0.0:8080

resources:
  reserved:
    cpus: 1
    memory_gb: 2048
