agent_id: "f7b27e21-eabb-4acb-8cd7-1d8113fd2237"
vm_store: /tmp

qemu:
  system_bin: qemu-system-x86_64
  img_bin: qemu-img

api:
  bind_endpoint: "127.0.0.1:50055"

controller:
  endpoint: "http://127.0.0.1:50051"
  key: test

db:
  url: sqlite:///tmp/db.sqlite

cvm:
  initrd: /tmp/artifacts/initramfs.cpio
  bios: /tmp/artifacts/OVMF.fd
  cpu:
    kernel: /tmp/artifacts/vmlinuz
    base_disk: /tmp/artifacts/disk.qcow2
    verity_disk: /tmp/artifacts/verity-hash-dev.raw
    verity_root_hash: /tmp/artifacts/verity-root-hash
  gpu:
    kernel: /tmp/artifacts/vmlinuz-gpu
    base_disk: /tmp/artifacts/disk-gpu.qcow2
    verity_disk: /tmp/artifacts/verity-hash-dev-gpu.raw
    verity_root_hash: /tmp/artifacts/verity-root-hash-gpu

sni_proxy:
  dns_subdomain: "workloads.nilcc.com"
  start_port_range: 10000
  end_port_range: 20000
  config_file_path: /etc/haproxy/haproxy.cfg
  ha_proxy_config_reload_command: sudo systemctl reload haproxy
  timeouts:
    connect: 5000
    server: 5000
    client: 5000
  max_connections: 100000

metrics:
  bind_endpoint: 0.0.0.0:8080

resources:
  reserved:
    cpus: 1
    memory_mb: 1024
