agent_id: "f7b27e21-eabb-4acb-8cd7-1d8113fd2237"
vm_store: /tmp

qemu:
  system_bin: qemu-system-x86_64
  img_bin: qemu-img

api:
  endpoint: "http://127.0.0.1:50051"
  key: test
  sync_interval: 10s

db:
  url: sqlite:///tmp/db.sqlite

